## Abzal Bacchus-- Random Forest ML Project

In [65]:
# TODO:  RandomForest for the ML project...clean then push

# https://intellipaat.com/blog/what-is-random-forest-algorithm-in-python/

# https://towardsdatascience.com/train-test-split-and-cross-validation-in-python-80b61beca4b6

In [31]:
pip3 install xgboost # why isnt it working?

SyntaxError: invalid syntax (<ipython-input-31-3debf2381671>, line 1)

# Importing all necessary modules

In [96]:
import pandas as pd
import numpy as np
import seaborn as sns
import datetime as dt
import random as rn
import matplotlib.pyplot as plt
import sklearn
from sklearn.feature_selection import chi2
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from scipy import stats
import math as math
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
# from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV
# from xgboost import XGBRegressor
from sklearn.metrics import accuracy_score
import math
from sklearn.ensemble import RandomForestRegressor

## Import train.csv

In [42]:
train = pd.read_csv('train.csv', index_col = 'Id')
train
# train = train.drop('Id', axis=0)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

# Defining features:
- Here, all the columns and rows are included, and the last column "SalePrice" is excluded

In [43]:
X = pd.DataFrame(train.iloc[:,:-1])
X

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal

In [66]:
chosen = ['LotFrontage','LotArea','LotShape','HouseStyle',
'OverallQual','OverallCond','YearBuilt','YearRemodAdd', 'CentralAir',
'MasVnrArea','1stFlrSF','2ndFlrSF','GrLivArea','Heating','Neighborhood',
'BsmtFullBath','FullBath','HalfBath','BedroomAbvGr','KitchenAbvGr',
'KitchenQual','Fireplaces','GarageType','GarageCars',
'WoodDeckSF','OpenPorchSF','PoolArea']

final = X[chosen].copy() # use final from here on in

# Handle missingness implementing Connors functions

In [67]:
#find numeric columns in given df,replace missing rows with column mean, return dataframe
def num_cleaner (df):
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    cl_df = pd.DataFrame()
    df2 = df.select_dtypes(include=numerics).copy() #only numeric columns
    nullCols = df2.isnull() #df of T/F, T if null (bool mask)
    means = df2.mean() #series of mean per column
    for c in df2:
        for r in range(0,len(df2)-1):
            if df2[c].iloc[r] and nullCols[c].iloc[r]:
                df2[c].iloc[r] = means[c]
              #print(df2[c].iloc[r]) #sanity check, last 8 should be 103.685 for MasVnrArea
    cl_df = df2.copy() #this will return only numeric features, need to add back type ob features after cleaning/dummify them
    return cl_df

new_cleaned_df = num_cleaner(final) # the new cleaned dataframe stored to a new variable 
new_cleaned_df

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,1stFlrSF,2ndFlrSF,GrLivArea,BsmtFullBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,Fireplaces,GarageCars,WoodDeckSF,OpenPorchSF,PoolArea
Id,,,,,,,,,,,,,,,,,,,,
1,65.0,8450,7,5,2003,2003,196.0,856,854,1710,1,2,1,3,1,0,2,0,61,0
2,80.0,9600,6,8,1976,1976,0.0,1262,0,1262,0,2,0,3,1,1,2,298,0,0
3,68.0,11250,7,5,2001,2002,162.0,920,866,1786,1,2,1,3,1,1,2,0,42,0
4,60.0,9550,7,5,1915,1970,0.0,961,756,1717,1,1,0,3,1,1,3,0,35,0
5,84.0,14260,8,5,2000,2000,350.0,1145,1053,2198,1,2,1,4,1,1,3,192,84,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,62.0,7917,6,5,1999,2000,0.0,953,694,1647,0,2,1,3,1,1,2,0,40,0
1457,85.0,13175,6,6,1978,1988,119.0,2073,0,2073,1,2,0,3,1,2,2,349,0,0
1458,66.0,9042,7,9,1941,2006,0.0,1188,1152,2340,0,2,0,4,1,2,1,0,60,0
1459,68.0,9717,5,6,1950,1996,0.0,1078,0,1078,1,1,0,2,1,0,1,366,0,0
1460,75.0,9937,5,6,1965,1965,0.0,1256,0,1256,1,1,1,3,1,0,1,736,68,0

In [68]:
#dummify object columns and return dataframe
def mass_dummify (df):
    df2 = df.select_dtypes(include=object).copy()
    dum_df = pd.get_dummies(df2) #currently 61 columns, no neighborhoods
    return dum_df

output = mass_dummify(final)

,LotShape_IR1,LotShape_IR2,LotShape_IR3,LotShape_Reg,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,...,KitchenQual_Ex,KitchenQual_Fa,KitchenQual_Gd,KitchenQual_TA,GarageType_2Types,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd
Id,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,1,0,0,0,0,0,1,...,0,0,1,0,0,1,0,0,0,0
2,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,1,0,0,0,0
3,1,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,1,0,0,0,0
4,1,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,1
5,1,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,0,0,0,1,0,0,0,0,0,1,...,0,0,0,1,0,1,0,0,0,0
1457,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,1,0,0,0,0
1458,0,0,0,1,0,0,0,0,0,1,...,0,0,1,0,0,1,0,0,0,0
1459,0,0,0,1,0,0,1,0,0,0,...,0,0,1,0,0,1,0,0,0,0
1460,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,1,0,0,0,0

## Here in one cell the two functions num_clean and ob_clean are being called and concatenated into a newly created df, named cl_df

In [86]:
# num clean + mass dummify in one cell here:
num_clean = num_cleaner(final).copy()
#cleaned
ob_clean = mass_dummify(final).copy()
#print(ob_clean.count())
#combine num & ob dataset
cl_df = pd.concat([num_clean,ob_clean],axis=1)
cl_df # run randomforest on this!!!!

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,1stFlrSF,2ndFlrSF,GrLivArea,...,KitchenQual_Ex,KitchenQual_Fa,KitchenQual_Gd,KitchenQual_TA,GarageType_2Types,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd
Id,,,,,,,,,,,,,,,,,,,,,
1,65.0,8450,7,5,2003,2003,196.0,856,854,1710,...,0,0,1,0,0,1,0,0,0,0
2,80.0,9600,6,8,1976,1976,0.0,1262,0,1262,...,0,0,0,1,0,1,0,0,0,0
3,68.0,11250,7,5,2001,2002,162.0,920,866,1786,...,0,0,1,0,0,1,0,0,0,0
4,60.0,9550,7,5,1915,1970,0.0,961,756,1717,...,0,0,1,0,0,0,0,0,0,1
5,84.0,14260,8,5,2000,2000,350.0,1145,1053,2198,...,0,0,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,62.0,7917,6,5,1999,2000,0.0,953,694,1647,...,0,0,0,1,0,1,0,0,0,0
1457,85.0,13175,6,6,1978,1988,119.0,2073,0,2073,...,0,0,0,1,0,1,0,0,0,0
1458,66.0,9042,7,9,1941,2006,0.0,1188,1152,2340,...,0,0,1,0,0,1,0,0,0,0
1459,68.0,9717,5,6,1950,1996,0.0,1078,0,1078,...,0,0,1,0,0,1,0,0,0,0
1460,75.0,9937,5,6,1965,1965,0.0,1256,0,1256,...,0,0,0,1,0,1,0,0,0,0

# Defining the target y
-The "SalePrice" column (target)

In [60]:
y = pd.DataFrame(train.iloc[:, -1])
y

      SalePrice
Id
1        208500
2        181500
3        223500
4        140000
5        250000
...         ...
1456     175000
1457     210000
1458     266500
1459     142125
1460     147500

[1460 rows x 1 columns]

# Here, a train_test_split is implemented:

In [87]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cl_df, y, test_size  = 0.30) # here I'm doing a 70/30 split but feel free to change

In [88]:
X_train

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,1stFlrSF,2ndFlrSF,GrLivArea,...,KitchenQual_Ex,KitchenQual_Fa,KitchenQual_Gd,KitchenQual_TA,GarageType_2Types,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd
Id,,,,,,,,,,,,,,,,,,,,,
46,61.000000,7658,9,5,2005,2005,412.0,1752,0,1752,...,1,0,0,0,0,1,0,0,0,0
471,70.049958,6820,8,5,1985,1985,0.0,1502,0,1502,...,0,0,1,0,0,1,0,0,0,0
1068,80.000000,9760,6,6,1964,1964,360.0,798,813,1611,...,0,0,0,1,0,1,0,0,0,0
496,60.000000,7879,4,5,1920,1950,0.0,720,0,720,...,0,0,0,1,0,0,0,0,0,0
478,105.000000,13693,9,5,2006,2006,772.0,2069,574,2643,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,50.000000,8000,6,6,1948,2002,0.0,972,0,972,...,0,0,0,1,0,0,0,0,0,1
847,75.000000,9317,7,5,1993,1993,137.0,1006,769,1775,...,0,0,1,0,0,1,0,0,0,0
423,100.000000,21750,5,5,1954,1954,0.0,988,0,988,...,0,0,0,1,0,1,0,0,0,0
67,70.049958,19900,7,5,1970,1989,287.0,2207,0,2207,...,0,0,0,1,0,1,0,0,0,0
1075,74.000000,8556,7,5,2006,2006,0.0,1240,0,1240,...,0,0,1,0,0,1,0,0,0,0

In [126]:
from sklearn.ensemble import RandomForestRegressor 

regressor = RandomForestRegressor(n_estimators = 20, random_state = 0) # feel free to alter these parameters 
regressor.fit(X_train, y_train)
y_prediction = regressor.predict(cl_df) # apply the prediction to the whole dataframe; namely cl_df 
y_prediction = np.delete(y_prediction, (-1), axis = 0) # remove last row
y_prediction.size

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

1459

In [100]:
y_prediction

array([208830.75      , 441332.3       , 172627.5       , 199552.4       ,
       133284.2       , 127797.5       , 276185.        , 194832.5       ,
       320273.05      , 596793.3       , 260232.5       , 160199.5       ,
       227369.2       , 128330.4       , 220511.4       , 118890.        ,
       348255.55      , 185103.5       , 156692.5       , 250665.65      ,
       120795.        , 258035.75      , 139376.75      , 147558.7       ,
       263794.        , 167860.        , 157775.        , 170971.1       ,
       104315.        , 143300.        , 231912.8       , 148987.95      ,
       118150.        ,  64997.5       , 174451.5       , 149542.5       ,
       161477.5       , 172844.5       ,  74450.        , 186064.        ,
        82800.        , 373067.15      , 121146.7       , 326828.05      ,
       130362.5       , 156980.        , 224621.2       , 162295.        ,
       319211.35      , 108892.35      , 135415.        , 128230.        ,
       399766.8       , 218201.5       , 107898.55      , 138675.        ,
       147027.5       , 279459.65      , 137670.        , 128747.5       ,
       162917.5       , 163495.        , 320221.75      , 174644.5       ,
       133160.        , 329890.75      , 249079.8       , 130435.        ,
       314418.75      , 126745.        , 119825.        , 382925.95      ,
       117370.        , 176535.        ,  89712.5       , 493424.1       ,
       166287.15      , 215020.        , 109385.        , 167997.5       ,
       177199.5       , 198185.        , 177697.        , 133495.        ,
       128245.        , 173782.        , 285285.        , 298085.        ,
       164080.        , 188019.5       , 119300.        , 144735.        ,
       114960.        , 252136.5       , 229153.3       , 231715.        ,
       102620.        , 157002.        , 171479.85      , 154655.        ,
       153170.        , 177880.        , 195360.        , 111397.95      ,
       182030.        , 130912.5       , 147705.        , 222670.        ,
       227818.25      , 119315.        , 165584.5       , 136037.5       ,
       219832.1       , 394320.05      , 148304.2       , 429065.        ,
       102210.        , 133400.        , 118245.        , 192750.        ,
       135720.        , 180575.        , 211045.        , 174030.        ,
       144562.5       , 192320.        , 306515.        , 221525.        ,
       364415.1       , 104025.        , 137290.        , 195297.25      ,
       109370.        , 206783.7       , 180034.3       ,  99020.        ,
       174298.65      , 128235.        , 133385.        , 114215.        ,
       176809.5       , 116625.4       , 148640.        , 138005.        ,
       114635.        , 254369.        , 141892.5       , 101920.        ,
       227364.5       , 117225.        , 144240.        , 322121.6       ,
       176945.        , 275412.9       , 262412.95      , 154940.        ,
       185320.        , 168960.        ,  71064.65      , 115905.        ,
       115293.8       , 175759.        , 175035.        , 150427.5       ,
       120985.        , 180140.        , 164057.5       , 193056.5       ,
       146607.5       ,  96400.        , 210742.8       , 284453.95      ,
       127383.75      , 142296.5       , 103490.        , 199159.        ,
       124965.        , 137222.95      , 167665.        , 133300.        ,
       190782.5       , 221945.5       ,  90924.3       , 156140.        ,
       428726.8       , 324650.2       , 306543.2       , 248554.        ,
       238121.7       , 230101.4       , 201285.        , 128425.4       ,
       163369.2       , 129758.2       , 224847.75      , 198677.65      ,
       123617.5       , 220518.        , 139040.        , 311265.55      ,
       252413.        , 186235.        , 103118.        , 124550.        ,
       145670.        , 141137.95      , 230551.3       , 204930.        ,
       120487.9       , 143882.5       , 157829.1       , 116625.        ,
       120040.4       , 125885.        , 139737.5       , 117122.5       ,
       109833.8       , 271177.5       , 157595.        , 147015.        ,
       213625.        ,  98960.        , 155987.3       , 198288.95      ,
       140275.        , 187500.        , 144095.        , 153920.45      ,
       186741.2       , 197575.        , 199110.        , 123118.8       ,
       153092.5       , 228660.6       , 353150.45      , 142470.        ,
       171646.2       ,  86583.2       , 116442.5       , 163250.        ,
       139000.        ,  86695.        , 161245.        , 136515.        ,
       133937.5       , 165890.        , 310205.5       , 111518.        ,
       162071.6       , 113820.        , 130180.        ,  93745.        ,
       365268.35      , 176688.5       , 149312.5       , 136997.5       ,
       178374.55      , 242450.        , 193070.5       , 137285.        ,
       286861.55      , 136009.15      , 268593.95      , 113093.75      ,
       129245.        , 160090.        , 341155.        , 205707.5       ,
       329109.3       , 268021.2       ,  92880.        , 190033.9       ,
       181006.3       , 172375.        , 129015.        , 275541.3       ,
       186065.        ,  97664.3       , 238309.7       , 163011.7       ,
       152345.        , 190507.5       , 118857.6       , 138246.25      ,
       115510.        , 123916.3       , 332533.9       , 271400.6       ,
       140545.        , 339963.25      , 146060.        , 103400.        ,
       266094.8       , 232376.9       , 403464.25      , 159620.        ,
       180109.5       , 128245.        , 297529.35      , 185658.7       ,
       225463.5       , 151130.        , 113924.        , 131266.7       ,
       291092.8       , 211603.9       , 244217.5       , 246033.75      ,
       120840.        , 175767.5       ,  87242.5       , 122680.        ,
       165780.        , 208603.95      , 159024.1       , 165214.        ,
       218530.        , 177900.        , 312552.55      , 186695.        ,
        88440.        , 139555.        , 191460.        , 297083.05      ,
       109120.        , 145321.75      , 230106.6       , 211146.8       ,
       149885.        , 117094.65      , 270710.65      , 106645.        ,
       147278.4       , 132528.55      , 143230.        , 149225.        ,
       150125.        , 213233.9       , 113587.5       , 239641.4       ,
       156870.25      , 206000.        , 112732.2       , 212965.        ,
       245016.25      , 152440.3       , 339691.25      , 421548.95      ,
        96192.5       , 241880.6       , 170356.55      , 131875.        ,
       141446.7       , 215533.4       , 124145.        , 245372.95      ,
       165080.45      , 141437.5       , 128970.        ,  89975.        ,
       107110.        , 149045.3       , 148712.5       , 169650.35      ,
       131811.7       , 170408.15      , 136587.28333333, 208700.        ,
       192058.9       , 149397.95      , 136110.        , 236619.2       ,
        87085.55      ,  64425.55      , 122912.5       , 399526.45      ,
       133257.5       ,  97480.        , 280715.35      , 154619.35      ,
       128075.        , 139270.        ,  90360.        , 263361.75      ,
       295736.35      , 147767.825     , 136712.5       , 147925.        ,
       130046.7       , 248440.5       , 140562.5       , 167085.        ,
       220156.5       , 111575.4       , 142191.25      , 114425.        ,
       206969.95      , 237650.4       , 125626.7       , 113150.        ,
       122340.        ,  97375.        , 106763.75      , 329967.25      ,
       154265.        , 258372.8       , 149300.        , 224551.25      ,
       226433.1       , 255641.75      , 172702.5       , 385711.85      ,
       123605.        , 245194.6       ,  99085.        , 162234.        ,
       166945.        , 137625.        , 239220.        , 139385.        ,
       168487.5       , 120765.4       , 247083.65      , 155248.45      ,
       120665.        , 224872.        , 184510.        , 132817.5       ,
       192715.        , 143845.        , 423424.2       , 153740.        ,
       277690.        , 118700.        , 196771.2       , 155569.35      ,
       292395.        , 140640.        ])

In [110]:

print('Mean error: %.2f' % mean_absolute_error(y_test, y_prediction))
print('Mean squared error: %.2f' % mean_squared_error(y_test, y_prediction))
print('RMSE: %.4f'  % np.sqrt(mean_squared_error(y_test, y_prediction)))
print('R squared for train: %.4f'  % regressor.score(X_train,y_train))
print('R squared for test: %.4f'  % regressor.score(X_test,y_test))

Mean error: 18619.36
Mean squared error: 854129322.44
RMSE: 29225.4910
R squared for train: 0.9666
R squared for test: 0.8757

In [128]:
# export predict as csv and then on to kaggle to see:

prediction_df = pd.DataFrame()
prediction_df['Id'] = range(1461, 2920) # new Id column

prediction = y_prediction.round(0).astype(int)
prediction_df['SalePrice'] = prediction # make a new column named SalePrice 
prediction_df.to_csv('./prediction_output.csv') # name of output file, contains Id + SalePrice

In [ ]:
# code snippet pulled from online might be helpful

rf = RandomForestRegressor(bootstrap=False, criterion='mse', max_depth=19,
                      max_features=23, max_leaf_nodes=None,
                      min_impurity_decrease=1e-06, min_impurity_split=None,
                      min_samples_leaf=3, min_samples_split=2,
                      min_weight_fraction_leaf=0.0001, n_estimators=58,
                      n_jobs=None, oob_score=False, random_state=108, verbose=0, # change the random_state to any#
                      warm_start=False)

print(rf)
rf.fit(X_train,y_train)
print(get_error(X_train, y_train, X_test, y_test, rf))
mean_squared_error(y_test, rf.predict(X_test))